Fixed eapol_test program checks. Script is now able to work with exact path to program, program mentioned only by it's name (and being on $PATH) or with program in actual directory.

diff --git a/rad_eap_test b/rad_eap_test
--- a/rad_eap_test
+++ b/rad_eap_test
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# $Id: rad_eap_test,v 1.10 2006-07-21 09:46:54 semik Exp $                       
+# $Id: rad_eap_test,v 1.11 2006-07-21 09:54:09 semik Exp $                       
                                                                                 
 # rad_eapol_test nagios compatible wraper around eapol_test                     
 # Copyright (c) 2005-2006, Pavel Poláček <polish@pf.ujep.cz>                   
@@ -51,10 +51,14 @@ RET_EAP_FAILED=4
 RET_RADIUS_NOT_AVAIL=5
 
 # exist eapol_test program ?
-if [ ! -x "$EAPOL_PROG" ]; then
-    if [ ! -x `which $EAPOL_PROG` ]; then
-	echo "eapol_test program \"$EAPOL_PROG\" not found"
-	exit 3;
+if [ ! -x "$EAPOL_PROG" ]; then # exact path?
+    if [ ! -x `which $EAPOL_PROG` ]; then # is program on path?
+        if [ -x "./$EAPOL_PROG" ]; then # is program in actual directory?
+           EAPOL_PROG="./$EAPOL_PROG"
+        else
+	   echo "eapol_test program \"$EAPOL_PROG\" not found"
+	   exit 3;
+        fi
     fi
 fi
 
